version: '3'

services:
  
  db:
    image: postgres
    environment:
      POSTGRES_USER: rdmo
      POSTGRES_PASSWORD: rdmo
      POSTGRES_DB: rdmo

  web:
    build: .
    image: dainst/rdmo
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - default
      - web
    deploy:
      labels:
        - "traefik.docker.network=web"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:rdmo.test.idai.world"
        - "traefik.port=8000"

networks:
  web:
    external: true
